version: '3'

set: [errexit, pipefail]

vars:
  CHARTS:
    map:
      kyverno:
        name: kyverno
        url: https://kyverno.github.io/kyverno/
        app: kyverno
      argo:
        name: argo
        url: https://argoproj.github.io/argo-helm
        app: argo-cd
      crossplane:
        name: crossplane-stable
        url: https://charts.crossplane.io/stable
        app: crossplane
      stakater:
        name: stakater
        url: https://stakater.github.io/stakater-charts
        app: reloader
      prometheus:
        name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
        app: prometheus

tasks:
  default:
    desc: "Create helm wrappers for all charts"
    summary: "Entry point that processes all charts defined in CHARTS map and creates wrapper directories with Chart.yaml"
    cmds:
      - task: helmWrapper:main

  helmWrapper:main:
    desc: "Process all configured charts"
    summary: "Orchestrates the full workflow: checks requirements, adds Helm repos, updates them, and processes all charts"
    aliases: [setup, init]
    cmds:
      - task: required:check
      - task: helm:repositories:add:all
      - task: helm:repositories:update
      - task: helmWrapper:process:all

  required:check:
    desc: "Verify required CLI tools"
    summary: "Checks that helm, yq, and git are installed on the system before proceeding"
    internal: true
    cmds:
      - command -v helm >/dev/null 2>&1 && echo "✅ Helm" || { echo "❌ helm could not be found. Please install helm."; exit 1; }
      - command -v yq   >/dev/null 2>&1 && echo "✅ yq"   || { echo "❌ yq could not be found. Please install yq."; exit 1; }
      - command -v git  >/dev/null 2>&1 && echo "✅ git"  || { echo "❌ git could not be found. Please install git."; exit 1; }

  helm:repositories:add:all:
    desc: "Add all Helm repositories"
    summary: "Iterates through CHARTS map and adds each repository to Helm, skipping if already exists"
    internal: true
    cmds:
      - |
        {{range $key, $chart := .CHARTS}}
        echo "➕ Adding repository: {{$chart.name}}"
        helm repo add "{{$chart.name}}" "{{$chart.url}}" 2>/dev/null || echo "ℹ️  Repository {{$chart.name}} already exists"
        {{end}}
        echo "✅ All repositories added"

  helm:repositories:update:
    desc: "Update all Helm repositories"
    summary: "Refreshes the local cache of all added Helm repositories to fetch latest chart versions"
    internal: true
    cmds:
      - helm repo update
      - cmd: echo "✅ Repositories updated"
        silent: true

  helmWrapper:process:all:
    desc: "Process and create wrappers for all charts"
    summary: "Loops through all charts: copies config template, fetches chart metadata from Helm, and generates Chart.yaml wrapper"
    internal: true
    preconditions:
      - sh: '[ -d "config" ]'
        msg: "❌ Config directory not found. Please ensure 'config' directory exists with template files."
    cmds:
      - |
        {{range $key, $chart := .CHARTS}}
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "🔄 Processing chart: {{$chart.app}}"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        
        # Copy template directory
        mkdir -p "{{$chart.app}}"
        rm -rf "{{$chart.app}}"/*
        cp -r config/* "{{$chart.app}}/"
        echo "📁 Config copied to {{$chart.app}}"
        
        # Update Chart.yaml
        cd "{{$chart.app}}"
        HELM_CHART="$(helm show chart {{$chart.name}}/{{$chart.app}})"
        
        export HELM_CHART_VERSION="$(echo "$HELM_CHART" | yq '.version')"
        export HELM_APP_VERSION="$(echo "$HELM_CHART" | yq '.appVersion')"
        export HELM_SOURCES="$(echo "$HELM_CHART" | yq '.sources[0]')"
        
        yq -i '
          .name = "{{$chart.app}}-wrapper" |
          .description = "Wrapper for {{$chart.name}} {{$chart.app}}" |
          .type = "application" |
          .version = "1.0.0" |
          .appVersion = strenv(HELM_APP_VERSION) |
          .maintainers = [{"name":"Mathod"}] |
          .dependencies = [{
            "name":"{{$chart.app}}",
            "version": strenv(HELM_CHART_VERSION),
            "repository":"{{$chart.url}}"
          }] |
          .sources = [strenv(HELM_SOURCES)]
        ' Chart.yaml
        
        echo "📝 Chart.yaml updated (version: $HELM_CHART_VERSION, appVersion: $HELM_APP_VERSION)"
        cd ..
        
        echo "✅ {{$chart.app}} wrapper created successfully"
        {{end}}
        echo ""
        echo "🎉 All chart wrappers have been created!"

  clean:
    desc: "Remove all generated chart wrapper directories"
    summary: "Deletes all chart directories created by the wrapper process, based on the CHARTS map configuration"
    cmds:
      - |
        {{range $key, $chart := .CHARTS}}
        if [ -d "{{$chart.app}}" ]; then
          echo "🗑️  Removing {{$chart.app}}/"
          rm -rf "{{$chart.app}}"
        fi
        {{end}}
        echo "✅ Cleanup completed!"

  current_version:
    desc: "Get upstream chart versions for all wrappers"
    summary: "Reads dependencies[0].version from each Chart.yaml"
    cmds:
      - |
        {{range $key, $chart := .CHARTS}}
        if [ ! -f "{{$chart.app}}/Chart.yaml" ]; then
          echo "❌ {{$chart.app}}/Chart.yaml not found"
          exit 1
        fi

        CHART_VERSION="$(yq eval '.dependencies[0].version' {{$chart.app}}/Chart.yaml)"
        echo "📦 {{$chart.app}}: ${CHART_VERSION}"
        {{end}}

  values:fetch:
    desc: "Fetch official values.yaml as examples for all wrappers"
    summary: "Downloads upstream default values and saves them in values.example files"
    cmds:
      - echo "📋 Fetching official values for all chart wrappers..."
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - |
        {{range $key, $chart := .CHARTS}}
        if [ -d "{{$chart.app}}" ] && [ -f "{{$chart.app}}/values.example" ]; then
          echo -n "📦 {{$chart.app}}: "
          
          # Determine chart name
          CHART_NAME="{{if $chart.chart_name}}{{$chart.chart_name}}{{else}}{{$chart.app}}{{end}}"
          
          # Create a backup to work with
          cp "{{$chart.app}}/values.example" "{{$chart.app}}/values.example.tmp"
          
          # Replace placeholders
          sed -i "s|CHART_APP_NAME|{{$chart.app}}|g" "{{$chart.app}}/values.example.tmp"
          sed -i "s|CHART_URL|{{$chart.url}}|g" "{{$chart.app}}/values.example.tmp"
          sed -i "s|CHART_REPO|{{$chart.name}}|g" "{{$chart.app}}/values.example.tmp"
          sed -i "s|CHART_NAME|${CHART_NAME}|g" "{{$chart.app}}/values.example.tmp"
          sed -i "s|GENERATED_DATE|$(date '+%Y-%m-%d %H:%M:%S')|g" "{{$chart.app}}/values.example.tmp"
          
          # Move the processed header to final file
          mv "{{$chart.app}}/values.example.tmp" "{{$chart.app}}/values.example"
          
          # Append the actual values
          if helm show values "{{$chart.name}}/${CHART_NAME}" >> "{{$chart.app}}/values.example" 2>/dev/null; then
            echo "✅ Done"
          else
            echo "❌ Failed to fetch values"
          fi
        else
          echo "⚠️  {{$chart.app}}: Directory or values.example not found"
        fi
        {{end}}
      - echo ""
      - echo "✅ Values fetch completed!"

  update:check:
    desc: "Check for available updates for all charts"
    cmds:
      - echo "🔍 Checking for chart updates..."
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - helm repo update >/dev/null 2>&1
      - |
        {{range $key, $chart := .CHARTS}}
        if [ -f "{{$chart.app}}/Chart.yaml" ]; then
          # Get current versions from wrapper
          CURRENT_CHART="$(yq eval '.dependencies[0].version' {{$chart.app}}/Chart.yaml)"
          CURRENT_APP="$(yq eval '.appVersion' {{$chart.app}}/Chart.yaml)"

          # Get latest versions from upstream
          CHART_NAME="{{if $chart.chart_name}}{{$chart.chart_name}}{{else}}{{$chart.app}}{{end}}"
          UPSTREAM_INFO="$(helm show chart {{$chart.name}}/${CHART_NAME})"
          LATEST_CHART="$(echo "$UPSTREAM_INFO" | yq '.version')"
          LATEST_APP="$(echo "$UPSTREAM_INFO" | yq '.appVersion')"

          # Check if update is available
          if [ "$CURRENT_CHART" != "$LATEST_CHART" ] || [ "$CURRENT_APP" != "$LATEST_APP" ]; then
            echo "🔄 {{$chart.app}}:"
            if [ "$CURRENT_CHART" != "$LATEST_CHART" ]; then
              echo "   Chart: $CURRENT_CHART → $LATEST_CHART"
            fi
            if [ "$CURRENT_APP" != "$LATEST_APP" ]; then
              echo "   App:   $CURRENT_APP → $LATEST_APP"
            fi
          else
            echo "✅ {{$chart.app}}: $CURRENT_CHART (app: $CURRENT_APP) - up to date"
          fi
        else
          echo "⚠️  {{$chart.app}}: Chart.yaml not found"
        fi
        {{end}}
      - echo ""
      - echo "💡 Run 'task update:single -- <chart-name>' to update a specific chart"

###################################################################################################

#  search_existing_versions:
#    cmds:
#      - "echo 'No new version provided. Searching the repository for existing versions...'"
#      - "printf '%-15s %-15s %s\\n' 'Version' 'App Version' 'Current'"
#      - "helm search repo temp/$chart -l --output json | jq -r '.[] | \"\(.version) \(.app_version)\"' | awk -v cv=\"$current_version\" '{if (\$1 == cv) printf \"%-15s %-15s %s\\n\", \$1, \$2, \"*\"; else printf \"%-15s %-15s %s\\n\", \$1, \$2, \"\"}'"
#      - "task remove_temp_repo"
#      - "exit 0"
#
#  verify_version_exists:
#    cmds:
#      - "search_results=$(helm search repo temp/$chart --version \"$new_version\" --output json)"
#      - "if [ \"\$(echo $search_results | jq -r '.[0].app_version')\" == 'null' ]; then"
#      - "    echo 'Version does not exist'"
#      - "    task remove_temp_repo"
#      - "    exit 1"
#      - "fi"
#      - "app_version=$(echo $search_results | jq -r '.[0].app_version')"
#      - "echo 'Version exists, app_version is $app_version'"
#
#  update_chart_yaml:
#    cmds:
#      - "yq eval -i \".version = \\\"$new_version\\\"\" cnpg/Chart.yaml"
#      - "yq eval -i '(.dependencies[0].version) |= \"'$new_version'\"' cnpg/Chart.yaml"
#      - "yq eval -i \".appVersion = \\\"$app_version\\\"\" cnpg/Chart.yaml"
#      - "task remove_temp_repo"
#      - "echo 'Updated cnpg/Chart.yaml with version $new_version and appVersion $app_version'"
#
#  update_dependencies:
#    cmds:
#      - "helm dependency update cnpg > /dev/null"
#
#  check_tag_exists:
#    cmds:
#      - "if git rev-parse \"$new_version\" >/dev/null 2>&1; then"
#      - "    echo 'Tag already exists, why do you want to add it again? Exiting...'"
#      - "    exit 1"
#      - "fi"
#
#  commit_and_push_changes:
#    cmds:
#      - "git add ."
#      - "git commit -m 'Changed version $new_version and appVersion $app_version'"
#      - "git tag $new_version"
#      - "git push origin $new_version --tags"