apiVersion: v2
name: argo-cd-wrapper
description: Wrapper for argo argo-cd
type: application
version: 1.0.0
appVersion: "v3.2.3"
maintainers:
  - name: Mathod
dependencies:
  - name: argo-cd
    version: 9.2.3
    repository: https://argoproj.github.io/argo-helm
sources:
  - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
