version: '3'

set: [errexit, pipefail]

# VARIABLES ########################################################################################

vars:
  # APPLICATION
  APP_NAME: '{{.APP_NAME}}'
  # GITLAB
  GITLAB_GROUP_ID: 120554361
  VISIBILITY: '{{.VISIBILITY | default "public"}}'
  # CHARTS
  CHARTS:
    map:
      kyverno:
        name: kyverno
        url: https://kyverno.github.io/kyverno/
        app: kyverno
      argo:
        name: argo
        url: https://argoproj.github.io/argo-helm
        app: argo-cd
      crossplane:
        name: crossplane-stable
        url: https://charts.crossplane.io/stable
        app: crossplane
      stakater:
        name: stakater
        url: https://stakater.github.io/stakater-charts
        app: reloader
      prometheus:
        name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
        app: prometheus
      knative:
        name: knative-operator
        url: https://knative.github.io/operator
        app: knative-operator

# INCLUDES #########################################################################################

includes:

# MAIN #############################################################################################

tasks:
  default:
    desc: ""
    summary: ""
    aliases: [setup, init]
    cmds:
      - task: helmWrapper:main
  
  helmWrapper:main:
    desc: ""
    summary: ""
    cmds:
      - echo ""
      - task: required:main
      - task: helm:main
      - task: directory:main
      - task: values:main

# REQUIRED CHECK ###################################################################################

  required:main:
    desc: ""
    summary: ""
    cmds:
      - task: required:packages
      - task: required:gitlab:auth

  required:packages:
    desc: ""
    summary: ""
    internal: true
    silent: true
    cmds:
      - echo "required:packages"
      - command -v helm >/dev/null 2>&1 && echo "✅ helm" || { echo "❌ helm could not be found. Please install helm."; exit 1; }
      - command -v yq   >/dev/null 2>&1 && echo "✅ yq"   || { echo "❌ yq could not be found. Please install yq."; exit 1; }
      - command -v glab >/dev/null 2>&1 && echo "✅ glab" || { echo "❌ glab could not be found. Please install git."; exit 1; }
      - command -v sd   >/dev/null 2>&1 && echo "✅ sd"   || { echo "❌ sd could not be found. Please install sd."; exit 1; }
      - echo ""

  required:gitlab:auth:
    desc: ""
    summary: ""
    internal: true
    silent: true
    cmds:
      - echo "required:gitlab:auth"
      - glab auth status >/dev/null 2>&1 && echo "✅ glab authenticated" || { echo "❌ glab is not authenticated. Please authenticate with 'glab auth login'."; exit 1; }
      - echo ""

# HELM #############################################################################################

  helm:main:
    desc: ""
    summary: ""
    cmds:
      - task: helm:add:repositories
      - task: helm:update:repositories

  helm:add:repositories:
    desc: "Add all Helm repositories"
    internal: true
    cmds:
      - echo "helm:add:repositories"
      - |
        {{range $key, $chart := .CHARTS}}
        if helm repo list | grep -q "^{{$chart.name}}\s"; then
          echo "⏭️  {{$chart.name}} already configured"
        else
          helm repo add "{{$chart.name}}" "{{$chart.url}}" >/dev/null 2>&1 && \
            echo "✅ {{$chart.name}} added" || \
            echo "❌ {{$chart.name}} failed"
        fi
        {{end}}
      - echo "✅ All repositories ready"
      - echo ""

  helm:update:repositories:
    desc: "Update all Helm repositories"
    summary: "Refreshes the local cache of all added Helm repositories to fetch latest chart versions"
    internal: true
    cmds:
      - echo "helm:update:repositories"
      - helm repo update
      - echo "✅ Repositories updated"
      - echo ""

# DIRECTORY ########################################################################################

  directory:main:
    desc: ""
    summary: ""
    cmds:
      - task: directory:copy:template
      - task: directory:rename:charts
      - task: directory:rename:applicationSet

  directory:copy:template: # OK
    desc: "Copy the template to all directories"
    summary: "Copies the template into all application directories"
    cmds:
      - echo "directory:copy:template"
      - |
        {{range $key, $chart := .CHARTS}}
        cp -r template {{$chart.app}}
        echo "✅ {{$chart.app}} copied"
        {{end}}
      - echo ""

  directory:rename:charts: # OK
    desc: "Rename charts directories"
    summary: "Renames the charts folder inside each application directory."
    internal: true
    cmds:
      - echo "directory:rename:charts"
      - |
        {{range $key, $chart := .CHARTS}}
        mv {{$chart.app}}/charts/APP_NAME {{$chart.app}}/charts/{{$chart.app}} 2>/dev/null && \
          echo "✅ {{$chart.app}} renamed" || \
          echo "⏭️  {{$chart.app}} skipped"
        {{end}}
      - echo ""

  directory:rename:applicationSet: # OK
    desc: "Rename application set YAML files"
    summary: "Renames the application set YAML files inside the apps folders"
    internal: true
    cmds:
      - echo "directory:rename:applicationSet"
      - |
        {{range $key, $chart := .CHARTS}}
        if [ -f "{{$chart.app}}/apps/APP_NAME-applicationSet.yaml" ]; then
          mv "{{$chart.app}}/apps/APP_NAME-applicationSet.yaml" "{{$chart.app}}/apps/{{$chart.app}}-applicationSet.yaml"
          echo "✅ {{$chart.app}} applicationSet renamed"
        else
          echo "⏭️  {{$chart.app}}/apps/APP_NAME-applicationSet.yaml not found"
        fi
        {{end}}
      - echo ""

# APPLICATIONSET ###################################################################################

# CHART ############################################################################################

# VALUES ###########################################################################################

  values:main:
    desc: ""
    summary: ""
    cmds:
      - task: values:fetch:default
      - task: values:update:placeholders

  values:fetch:default:
    desc: "Fetch official values.yaml for the specified chart and append to values.yaml.example"
    summary: "Downloads the default values for a chart and appends them to values.yaml.example"
    cmds:
      - echo "values:fetch:chart"
      - helm show values "{{.CHARTS.kyverno.name}}/{{.CHARTS.kyverno.app}}" >> "{{.CHARTS.kyverno.app}}/charts/{{.CHARTS.kyverno.app}}/values.yaml.default" 2>/dev/null
      - echo "✅ Values fetch completed!"

  values:update:placeholders:
    desc: "Update values.example with correct placeholders"
    cmds:
      - echo "Updating placeholders..."
      - sd "CHART_URL" "{{.CHARTS.kyverno.url}}" "{{.CHARTS.kyverno.app}}/charts/{{.CHARTS.kyverno.app}}/values.yaml.default"
      - sd "CHART_REPO" "{{.CHARTS.kyverno.name}}" "{{.CHARTS.kyverno.app}}/charts/{{.CHARTS.kyverno.app}}/values.yaml.default"
      - sd "CHART_NAME" "{{.CHARTS.kyverno.app}}" "{{.CHARTS.kyverno.app}}/charts/{{.CHARTS.kyverno.app}}/values.yaml.default"
      - sd "CHART_APP_NAME" "{{.CHARTS.kyverno.app}}" "{{.CHARTS.kyverno.app}}/charts/{{.CHARTS.kyverno.app}}/values.yaml.default"
      - sd "GENERATED_DATE" "$(date '+%Y-%m-%d %H:%M:%S')" "{{.CHARTS.kyverno.app}}/charts/{{.CHARTS.kyverno.app}}/values.yaml.default"
      - echo "✅ Done!"

# GITLAB ###########################################################################################

  gitlab:create:repository:
    desc: ""
    summary: ""
    requires:
      vars: [APP_NAME]
    env:
      PATH: ./{{.APP_NAME}}
    cmds:
      - glab repo create {{.APP_NAME}} --group {{.GITLAB_GROUP_ID}} --{{.VISIBILITY}}







      #- git init
      #- git add .
      #- git commit -m "Initial commit"
      #- git remote add origin git@gitlab.com:mathod-io/infrastructure/services/{{.APP_NAME}}.git
      #- git push -u origin main

# STANDALONE #######################################################################################

  clean:
    desc: "Remove all generated chart wrapper directories"
    summary: "Deletes all chart directories created by the wrapper process, based on the CHARTS map configuration"
    cmds:
      - |
        {{range $key, $chart := .CHARTS}}
        if [ -d "{{$chart.app}}" ]; then
          echo "🗑️  Removing {{$chart.app}}/"
          rm -rf "{{$chart.app}}"
        fi
        {{end}}
        echo "✅ Cleanup completed!"

# HELP #############################################################################################