apiVersion: v2 
name: APP_NAME-wrapper 
description: Wrapper for REPO_NAME APP_NAME
type: application 
version: 1.0.0 
appVersion: "APP_VERSION" 
maintainers: 
  - name: Mathod
    email: mathod@mathod.io

dependencies:
  - name: APP_NAME 
    version: CHART_VERSION
    repository: REPO_URL