{{- range .Values.providers }}
{{- if .enabled }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ .name }}
  namespace: crossplane-system
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: provider
spec:
  package: {{ .package }}
  {{- if $.Values.controllerConfig.enabled }}
  controllerConfigRef:
    name: aws-controller-config
  {{- end }}
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  packagePullPolicy: IfNotPresent
{{- end }}
{{- end }}
