apiVersion: v2
name: knative-operator-wrapper
description: Wrapper for knative-operator knative-operator
type: application
version: 1.0.0
appVersion: "null"
maintainers:
  - name: Mathod
dependencies:
  - name: knative-operator
    version: 1.20.0
    repository: https://github.com/ayevbeosa/knative-operator
sources:
  - https://github.com/knative/operator
